services:
  server:
    build:
      context: server
    image: nodejs
    env_file: .env
    ports:
      - "81:3000"
    volumes:
      - ./server:/code:ro
      - ./server/package.json:/code/package.json
      - ./server/package-lock.json:/code/package-lock.json
    networks:
      - app-network
    command: npm run start
    depends_on:
      - database
  client:
    build:
      context: client
    env_file: .env
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - server
  database:
    image: 'postgres:latest'
    env_file: .env
    ports:
      - 15432:5432
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
  nginx:
    build:
      context: reverse-proxy
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network
    depends_on:
      - server
      - client
      - database
networks:
  app-network: